### ISSUE TITLE
getWIOT function

### ISSUE THREAD

**Issue by MatRegen** [bquast/wiod#4]
When trying to load the updated WIOT data (i.e. 2012-2016) using the ``getWIOT`` function, one receives the following error message:
`` wiod.list <- list()
for(this.year in 2000:2014) {
 wiod.list[[as.character(this.year)]] <- getWIOT(period = this.year, format = "list")}
 ``

> Error in readRDS(file = gzcon(url(paste0(base.url, "WIOT", period, "_",  : 
>   cannot open the connection
> In addition: Warning message:
> In readRDS(file = gzcon(url(paste0(base.url, "WIOT", period, "_",  :
>   "internal" method cannot handle https redirection to: 'https://wiiw.ac.at/files/staff-content/reiter/WIOT2000_October16_ROW_list.rds'
> 

It seems like it fails to connect to the base URL.

**Comment by zauster** [comment]
solved in #5
